FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt requirements-worker.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-worker.txt

COPY src/ src/

ENV PYTHONPATH=/app/src
ENV SHOMER_CELERY_BROKER_URL=redis://redis:6379/0

CMD ["celery", "-A", "shomer.worker", "worker", "--loglevel=info"]
