apiVersion: v2
name: shomer
description: Helm chart for the Shomer OIDC/OAuth2 authentication service
type: application
version: "0.2.0"
appVersion: "0.2.0"
home: https://github.com/goabonga/test0
sources:
  - https://github.com/goabonga/test0
maintainers:
  - name: Chris
    email: goabonga@pm.me
